name: "Git Backup Action"
description: "Composit GitHub Action to create backup of all organization repo on AWS s3"

inputs:
  token:
    description: "Personal access token to handle the repos"
    required: true
  org:
    description: "GitHub organization name"
    required: true
  s3-bucket:
    description: "Destination S3 bucket"
    required: true
  role-to-assume:
    description: "IAM role ARN to assume via OIDC"
    required: true
  aws-region:
    description: "AWS region (default eu-west-1)"
    required: false
    default: "eu-west-1"
  prefix:
    description: "Prefix in the bucket (daily / weekly / monthly)"
    required: true

runs:
  using: "composite"
  steps:
    - id: repos
      uses: octokit/graphql-action@v2.3.2
      with:
        query: |
          {
            organization(login: "${{ inputs.org }}") {
              repositories(first: 100, isFork: false) {
                nodes { name }
              }
            }
          }
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Mirror & upload
      shell: bash
      env:
        OUT: /tmp/backup
        PREFIX: ${{ inputs.prefix }}
        BUCKET: ${{ inputs.s3-bucket }}
        REPO_JSON: ${{ steps.repos.outputs.data }}
        ORG: ${{ inputs.org }}          
        TOKEN: ${{ inputs.token }}      
      run: |
        set -euo pipefail
        DATE=$(date -u +%Y-%m-%dT%H%M%S)
        mkdir -p "$OUT"

        echo "$REPO_JSON" | jq -r '.organization.repositories.nodes[].name' \
        | while read -r NAME; do
            git clone --mirror \
              "https://x-access-token:${TOKEN}@github.com/${ORG}/${NAME}.git" \
              "$OUT/$NAME.git"

            tar czf "$OUT/$NAME-$DATE.git.tar.gz" -C "$OUT" "$NAME.git"
            aws s3 cp "$OUT/$NAME-$DATE.git.tar.gz" \
              "s3://$BUCKET/$PREFIX/$NAME-$DATE.git.tar.gz"

            rm -rf "$OUT/$NAME.git" "$OUT/$NAME-$DATE.git.tar.gz"
        done